name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore POSv2.UI/POSv2.UI.csproj

    - name: Build
      run: dotnet build POSv2.UI/POSv2.UI.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish POSv2.UI/POSv2.UI.csproj --configuration Release --output ./publish
